// This file is auto-generated by @hey-api/openapi-ts

import {createClient, createConfig, type Options, urlSearchParamsBodySerializer} from '@hey-api/client-fetch';
import type {
    AuthJwtLoginData,
    AuthJwtLoginError,
    AuthJwtLoginResponse,
    AuthJwtLogoutError,
    AuthJwtLogoutResponse,
    RegisterRegisterData,
    RegisterRegisterError,
    RegisterRegisterResponse,
    ResetForgotPasswordData,
    ResetForgotPasswordError,
    ResetForgotPasswordResponse,
    ResetResetPasswordData,
    ResetResetPasswordError,
    ResetResetPasswordResponse,
    VerifyRequestTokenData,
    VerifyRequestTokenError,
    VerifyRequestTokenResponse,
    VerifyVerifyData,
    VerifyVerifyError,
    VerifyVerifyResponse,
    UsersCurrentUserError,
    UsersCurrentUserResponse,
    UsersPatchCurrentUserData,
    UsersPatchCurrentUserError,
    UsersPatchCurrentUserResponse,
    UsersUserData,
    UsersUserError,
    UsersUserResponse,
    UsersPatchUserData,
    UsersPatchUserError,
    UsersPatchUserResponse,
    UsersDeleteUserData,
    UsersDeleteUserError,
    UsersDeleteUserResponse,
    AuthenticatedRouteError,
    AuthenticatedRouteResponse
} from './types.gen';

export const client = createClient(createConfig());

/**
 * Auth:Jwt.Login
 */
export const authJwtLogin = <ThrowOnError extends boolean = false>(options: Options<AuthJwtLoginData, ThrowOnError>) => {
    return (options?.client ?? client).post<AuthJwtLoginResponse, AuthJwtLoginError, ThrowOnError>({
        ...options,
        ...urlSearchParamsBodySerializer,
        headers: {
            'Content-Type': 'application/x-www-form-urlencoded',
            ...options?.headers
        },
        url: '/auth/jwt/login'
    });
};

/**
 * Auth:Jwt.Logout
 */
export const authJwtLogout = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => {
    return (options?.client ?? client).post<AuthJwtLogoutResponse, AuthJwtLogoutError, ThrowOnError>({
        ...options,
        url: '/auth/jwt/logout'
    });
};

/**
 * Register:Register
 */
export const registerRegister = <ThrowOnError extends boolean = false>(options: Options<RegisterRegisterData, ThrowOnError>) => {
    return (options?.client ?? client).post<RegisterRegisterResponse, RegisterRegisterError, ThrowOnError>({
        ...options,
        url: '/auth/register'
    });
};

/**
 * Reset:Forgot Password
 */
export const resetForgotPassword = <ThrowOnError extends boolean = false>(options: Options<ResetForgotPasswordData, ThrowOnError>) => {
    return (options?.client ?? client).post<ResetForgotPasswordResponse, ResetForgotPasswordError, ThrowOnError>({
        ...options,
        url: '/auth/forgot-password'
    });
};

/**
 * Reset:Reset Password
 */
export const resetResetPassword = <ThrowOnError extends boolean = false>(options: Options<ResetResetPasswordData, ThrowOnError>) => {
    return (options?.client ?? client).post<ResetResetPasswordResponse, ResetResetPasswordError, ThrowOnError>({
        ...options,
        url: '/auth/reset-password'
    });
};

/**
 * Verify:Request-Token
 */
export const verifyRequestToken = <ThrowOnError extends boolean = false>(options: Options<VerifyRequestTokenData, ThrowOnError>) => {
    return (options?.client ?? client).post<VerifyRequestTokenResponse, VerifyRequestTokenError, ThrowOnError>({
        ...options,
        url: '/auth/request-verify-token'
    });
};

/**
 * Verify:Verify
 */
export const verifyVerify = <ThrowOnError extends boolean = false>(options: Options<VerifyVerifyData, ThrowOnError>) => {
    return (options?.client ?? client).post<VerifyVerifyResponse, VerifyVerifyError, ThrowOnError>({
        ...options,
        url: '/auth/verify'
    });
};

/**
 * Users:Current User
 */
export const usersCurrentUser = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<UsersCurrentUserResponse, UsersCurrentUserError, ThrowOnError>({
        ...options,
        url: '/users/me'
    });
};

/**
 * Users:Patch Current User
 */
export const usersPatchCurrentUser = <ThrowOnError extends boolean = false>(options: Options<UsersPatchCurrentUserData, ThrowOnError>) => {
    return (options?.client ?? client).patch<UsersPatchCurrentUserResponse, UsersPatchCurrentUserError, ThrowOnError>({
        ...options,
        url: '/users/me'
    });
};

/**
 * Users:User
 */
export const usersUser = <ThrowOnError extends boolean = false>(options: Options<UsersUserData, ThrowOnError>) => {
    return (options?.client ?? client).get<UsersUserResponse, UsersUserError, ThrowOnError>({
        ...options,
        url: '/users/{id}'
    });
};

/**
 * Users:Patch User
 */
export const usersPatchUser = <ThrowOnError extends boolean = false>(options: Options<UsersPatchUserData, ThrowOnError>) => {
    return (options?.client ?? client).patch<UsersPatchUserResponse, UsersPatchUserError, ThrowOnError>({
        ...options,
        url: '/users/{id}'
    });
};

/**
 * Users:Delete User
 */
export const usersDeleteUser = <ThrowOnError extends boolean = false>(options: Options<UsersDeleteUserData, ThrowOnError>) => {
    return (options?.client ?? client).delete<UsersDeleteUserResponse, UsersDeleteUserError, ThrowOnError>({
        ...options,
        url: '/users/{id}'
    });
};

/**
 * Authenticated Route
 */
export const authenticatedRoute = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => {
    return (options?.client ?? client).get<AuthenticatedRouteResponse, AuthenticatedRouteError, ThrowOnError>({
        ...options,
        url: '/authenticated-route'
    });
};